### ISSUE TITLE
[GNB] Many, many changes wanted.

### ISSUE THREAD

**Issue by Trilkin** [Nik-Potokar/XIVSlothCombo#141]
These are pretty simple:

Add Continuation To Main Combo (if the appropriate buffs are up)
Add Gnashing Fang Combo to Main Combo (ONLY if you've already started the combo to prevent you from accidentally wasting it)

**Comment by Iaotle** [comment]
Honestly GNB needs a general rework. 
* You should be able to double weave all of them in your No Mercy windows. 
* Gnashing Fang should easily be combo-able into your main combo.
* OGCD priorities are messed up I think, needs to be looked at.

**Comment by Trilkin** [comment]
> Honestly GNB needs a general rework.
> 
> * You should be able to double weave all of them in your No Mercy windows.
> * Gnashing Fang should easily be combo-able into your main combo.
> * OGCD priorities are messed up I think, needs to be looked at.

As long as Gnashing Fang is a separate option. There are moments where you don't want to immediately use it (P2S limit cut, for example)

**Comment by Iaotle** [comment]
Don't worry the whole point of this plugin is to provide options (see SMN).

**Comment by damolitionn** [comment]
Added the features you requested and also redid most of the things in GNB because it was done like someone read a TLDR of GNB without actually playing the class.

I wish I could have done things like add Bloodfest into the main combo and throw in No Mercy into the main combo but it messes up the opener. I guess it's fine if you're not optimising so you could start a fight with Bloodfest into No Mercy and then into the burst but it just feels wrong to do that, it already felt weird adding Rough Divide outside of buff windows. I guess if people request it I can add it as another modular option into the main combo.

**Comment by Trilkin** [comment]
You could add it as an option for the same reason bard has similar options, I'd figure: so they get used on cooldown. If you're trying to optimize, you're always going to do your opener manually. I'll test the changes out in savages once they get pushed out and reply here after a few runs. If all seems good, I'll close this ticket.

**Comment by damolitionn** [comment]
Yeah I can throw it in after you're satisfied with the base updates first. I've always been one to add things that I personally might use so it feels off to me to include those options but I can see it being used if you're super lazy and you don't worry too much about losing usage because of uptime.

**Comment by Trilkin** [comment]
Ye, I personally wouldn't use it. I don't use most of the bard or summoner options for the same reason. Too much automation actually ends up hurting rather than helping.

**Comment by Trilkin** [comment]
Okay I built the latest version myself since it hasn't been updated yet. The Gnashing Fang feature works, but it seems to override the Double Down one. If I, for example, No Mercy > Gnashing Fang and then run the main combo, Double Down will never come up even with the feature enabled.

**Comment by Trilkin** [comment]
As an addendum to the previous comment, the expected GCD priority on main combo during No Mercy is Double Down > Sonic Break > the Gnashing Fang combo > Burst Strike > 1-2-3. I know Burst Strike isn't there, but adding an option to add it to the main combo would also be welcome.

**Comment by Trilkin** [comment]
I built from the repo before the pushed update to test out the changes and noticed an odd problem. From an opening situation when I have to use Bloodfest to give me the charges for Double Down, Double Down actually doesn't go into the main combo even with the feature enabled. I have to do it manually during those incidents. Also adding a feature to have Burst Strike in the main combo during No Mercy would be neato.

**Comment by damolitionn** [comment]
Oh, the Double Down is an easy fix. I wasn't thinking about the opener at all so the conditions were set to the ammo always being 2. I'll add Burst Strike to main combo as well as the No Mercy one too, completely overlooked it seeing as I'm so used to using it manually. PR should be up quickly seeing as they're small fixes, I'm surprised everything else is holding up.

**Comment by PapaSteel** [comment]
What do we think about putting Blasting Zone on the Gnashing Fang/Continuation combo? The new No Mercy window timing guarantees it'll be up again usually right after the second step.

**Comment by damolitionn** [comment]
Wait, it isn't in the new Gnashing Fang combo? I have it set up after the 2nd GCD so it's stays in line with the DD GCD. Depending on ultimate reclears I might go back and add conditions for the old burst.

**Comment by Trilkin** [comment]
Yeah, you get used to using Burst Strike manually it doesn't really register 'wait, this is a part of my No Mercy block.' And Blasting Zone is in the new feature, but if it drifts too far, it never gets used. Same with the new main combo. You have to use it manually.

**Comment by damolitionn** [comment]
So would you prefer it used after the first GCD during the 30 sec windows?

**Comment by Trilkin** [comment]
Or just due to a death. It should probably still be used after the second GCD (Double Down,) but it could use a further check at maybe one other point of the rotation. Possibly after the Gnashing Fang combo is over. If it drifts too far, you're just going to have to use it manually (or just hold it at that point.)

**Comment by damolitionn** [comment]
I'm not going to lie this is taking a little longer because I'm adding the feature into Gnashing Fang as well because my muscle memory finds it so weird to press gnashing fang and then go to my Solid Barrel combo.

**Comment by damolitionn** [comment]
I decided to leave Blasting Zone as is and users can use it manually if it's drifted otherwise it's just messy trying to plan out how it would work (If Blasting Zone gets used at the end of the 30s window, does that mean there should be a check at the end of Gnashing Fang at the minute mark. But also, what if the tank died during No Mercy and Sonic Break and Bow Shock got drifted too, would there need to be checks for those because there's already a check for Blasting Zone.)

**Comment by Trilkin** [comment]
So I just built from source using your Pull, and whatever you did ended up causing feature conflicts. I'm trying to determine which features are conflicting, but it's a mess at the moment. Will get you more info when I'm clear on what's going on.

**Comment by damolitionn** [comment]
Ahh thanks, I'll fix those up.

**Comment by Trilkin** [comment]
The issue with Blasting Zone being preferred over a GCD when your GCD is ready is also still present. Trying to figure out if that's another feature conflict.

**Comment by Trilkin** [comment]
Another problem I'm finding is that something is changing Burst Strike, and breaking the Bloodfest > Burst Strike combo. This is still a useful combo to have to spend cartridges at the end of a fight.

**Comment by damolitionn** [comment]
I think I fixed most of the combo issues, but I can't seem to recreate Blasting Zone being preferred over a GCD. I 've set a check so that if can only be used while the GCD is rolling but I'd also like to recreate the issue too.

**Comment by PapaSteel** [comment]
I don't know, this still feels like a mess. It feels like no matter how I adjust things, I still get locked out of using Gnashing Fang during No Mercy, too many buttons just get replaced with burst strike combo exclusively.

**Comment by damolitionn** [comment]
Oh I haven't put up the new PR yet so the burst strike thing isn't fixed yet.

**Comment by damolitionn** [comment]
I think this should fix all the previous issues, well at least the Burst Strike definitely.

**Comment by Iaotle** [comment]
@damolitionn merged, let me know how it goes.

**Comment by Iaotle** [comment]
Also, if you don't mind, can you break up the logic as outlined earlier in this issue? It's such a mess. Just pull out the relevant bits and pieces and nest it so it doesn't repeat the same thing like 80 times.

**Comment by Trilkin** [comment]
The logic is FAR better now, and consistent after about three No Mercy windows so far. The grace time for Blasting Zone before it turns to the next GCD might be a little TOO short now, but I imagine that's easily tweakable. Going to test it in P1S shortly.

**Comment by Trilkin** [comment]
Definitely works really well right now. Outside of having to do Blasting Zone manually if it drifts, everything else is solid.

**Comment by damolitionn** [comment]
Got stuck doing a level 80 raid so I decided to just add the pre DD burst as well, but that's good to hear that everything's working.

@Iaotle Which issue? If you're talking about the original code you mentioned in your first post, I ended up rewriting most of the GNB stuff. Otherwise, I've spaghetti-ed my code too long to see how to break it apart for now.

**Comment by Iaotle** [comment]
@damolitionn I noticed an issue while playing btw: Blasting Zone isn't put on the gnashing fang combo, only on main combo outside of No Mercy window. Makes it a bit harder to press since you might have to switch the buttons you're spamming.

As for logic I meant extracting things you check for in every if/else condition. So if you check for 0.7 GCD remaining in every part of your if/else you should just put it in an if statement at the top.

**Comment by damolitionn** [comment]
I put out the wrong PR so I'll do another PR some time today for the rest of the features, but the 0.7 GCD was testing the delay but I've removed them because it's not really needed at the moment.

**Comment by damolitionn** [comment]
@Iaotle I can't replicate your issue with Blasting Zone, so after Abdomen Tear it's not using Blasting Zone?

**Comment by damolitionn** [comment]
Yep, it was because of the wrong PR. Blasting Zone was still used in the same order sub level 90, but like Trilkin said if any of the oGCDs drift out their window in the 30/60 rotation you're going to have to use it manually till it drifts back in.

**Comment by sauronshotdogs** [comment]
For someone who had a vague idea of how GNB worked, could you explain which, if any, of the current features for GNB are obsolete, which to enable for the full rework to work and how many buttons this reduces the whole chain to.

Thanks from ungo bungo brain warrior

**Comment by damolitionn** [comment]
No problem @sauronshotdogs..

All the current features should be working and none are obsolete, I've removed all the old ones I believe.

There's two ways to make the full rework work:
1. Toggle Gnashing Fang and Continuation on Main Combo, Sonic Break/Bow Shock/Blasting Zone on Main Combo, Double Down on Main Combo/Burst Strike Continuation. The Rough Divide options are up to you. This puts everything on the ST combo but you'd need to activate Gnashing Fang manually first.
2. Toggle Gnashing Fang Combo/Burst Strike Continuation. Does the same thing as option 1 but instead puts the rotation on Gnashing Fang, I prefer this way honestly because I don't have to switch from ST to Gnashing Fang back to ST and the button bloat is the same (ie. there's still 2 buttons to press).

I added the No Mercy burst on No Mercy because all the old features kept adding skills to No Mercy so it's up to you there but it won't use the 30s rotation.

If you got everything toggled and you don't drift any oGCDs it'll remove:
1. Double Down (That is if you're good with managing your resources and go into every No Mercy with 3 ammo/1 ammo and a Bloodfest)
2. Bow Shock
3. Danger Zone/Blasting Zone
4. Sonic Break
5. Bloodfest

So, in terms of actual buttons you'd be pressing. It'll look like: 

![image](https://user-images.githubusercontent.com/87623949/150728955-8e1ad66f-64ab-48c5-83d6-7f277d9d9755.png)

But, like Trilkin said, if you drift Double Down/Bow Shock/Danger Zone/Sonic Break outside of the 30/60 rotation then you'll have to manually use it but so far that hasn't been an issue for me yet.

**Comment by sauronshotdogs** [comment]
Wow, that's a very thorough and detailed explanation, thanks a lot. This answered every question I might have had

**Comment by Trilkin** [comment]
I'm just an autist that tries almost every situation :^) I didn't try just using the Gnashing Fang combo as like, my 'cooldown' button, though. I've been just initiating Gnashing Fang and then spamming main combo to finish it.

**Comment by ShennyUK** [comment]
Is it possible to add an opt out for the "extras" in the GF combo only keeping continuation?

**Comment by damolitionn** [comment]
@ShennyUK Yeah I can do that, well instead of an opt out it'll be an opt in similar to the main combo options.

**Comment by Iaotle** [comment]
@damolitionn Blasting Zone is still not on the combo whenever it comes off-cooldown. I suggest you just have it take a weave slot regardless of the current combo progress etc.

Also it would be nice to have Bow Shock on the AoE combo whenever you have no mercy up. Makes dealing with multiple enemies a lot easier.

**Comment by damolitionn** [comment]
That's so weird, I did my reclears for the week with no issue with Blasting Zone and I just did a synced level 80 EX just to test out the sub 90 rotation and I didn't get the issue. I wonder if it's a ping issue or you've some how got so much SkS that it's clipping Danger Zone. The question then is where for Blasting Zone. 

Say it is a ping/SkS issue, then Blasting Zone can't occupy the same GCD space every Gnashing Fang rotation. Hypothetically, we could weave it after Gnashing Fang, and then weave it after Savage Claw during the 30 second window, the issue there would be that the user would have to delay No Mercy for a GCD so that Blasting Zone comes back up for its spot in the No Mercy burst. The way I see it, if Blasting Zone isn't in the same GCD spot for each Gnashing Fang combo, it'll drift in either 30 or 60s combos. Then again, to fix this current issue you'd just delay Gnashing Fang for a GCD so that Blasting Zone would definitely be off CD.

Maybe I'm just used to the very cyclical cycle of GNB that I can't see a solution for where to put Blasting Zone for people who are having clipping issues. It either drifts off the No Mercy rotation or drifts off the 30s rotation.

Aside from that, yeah Bow Shock/DD on AoE sounds good.

**Comment by Iaotle** [comment]
@damolitionn So I'm using Blasting Zone as much as I can but I do notice it not being used in No Mercy windows if it drifts out of alignment. While one way to fix this is just to not drift it, I'm not a GNB main and I notice it drifting relatively often. Couldn't you just add it on the main combo whenever it's up regardless of any windows?

**Comment by Iaotle** [comment]
Oh also it can be double weaved usually and the No Mercy opener doesn't seem to do so automatically (e.g. I can press it during the window faster than the combo)

**Comment by sauronshotdogs** [comment]
Using the GF Continuation combo with all additions on + BS on Cont and BS to BF feature, is it correct that I have to manually weave in BF for the opener? I cannot get it to fire off the correct 123 No mercy opener without manually using BF

**Comment by Iaotle** [comment]
I weave bloodfest manually. It's super easy since it's on the Burst Strike button for me, and you have to slot that anyway.

**Comment by sauronshotdogs** [comment]
> I weave bloodfest manually. It's super easy since it's on the Burst Strike button for me, and you have to slot that anyway.

Just wanted to make sure, thanks!

**Comment by damolitionn** [comment]
Yeah, I guess it could have an extra bit of logic to use Bloodfest in No Mercy if there's only 1 cartridge but like Iaotle said you have to have Burst Strike slotted anyway.

@Iaotle Yeah I just can't seem to replicate the issue for me which is strange, but I guess I could? It might end up triple weaving just on the nature of when it comes up and if it's working for other people I wouldn't want to break the optimized rotation for a catch all solution. But if you'd like, you can go ahead and do the PR for it.

**Comment by PapaSteel** [comment]
Feels like the more skillspeed, the more drift I encounter. It felt odd at 2.43, but at 2.41 I find that no mercy is coming off CD the *second* gnashing fang is ready again, and if I don't mentally hesitate for a half-second every two gnashing rotations I ruin my entire burst.

What ss are y'all playing at?

**Comment by damolitionn** [comment]
So it is a SkS issue which I assumed it was. I'm playing at 2.41 at the moment. No Mercy is an ability though so it isn't affected by SkS so wouldn't it make sense that Gnashing Fang is coming up exactly every 60 second window? Unless you mean Gnashing Fang is coming up even right before No Mercy is

**Comment by PapaSteel** [comment]
That's correct. Granted, I'm not a great gunbreaker and it's fully possible I'm deeply misunderstanding the rotation. But this is how things shake out with 2.41sks and the 123NM opener over two minutes. Blasting Zone pops onto the main combo at 30s, at just after 1 minute I delay the gnashing fang so you can see it take a split second before no mercy appears.
(Sorry the cartridge tracker is way up top there)

https://www.youtube.com/watch?v=cjT6UeeVglk

**Comment by damolitionn** [comment]
Oh yeah that's going to happen seeing as at 2.41s, Gnashing Fang is at a 29s CD. It's just the nature of it, I could make the combo inaccessible leading up to No Mercy to stop that if people are on autopilot. Also, in your burst you're triple weaving during the DD GCD btw.

**Comment by Iaotle** [comment]
I think it's been sufficiently changed.
