### ISSUE TITLE
[BRD] Simple bard gets locked up

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/XIVSlothCombo#240]
Single target will get stuck on Empyreal Arrow and other longer cd abilities if original target will die before finishing opener.

Will also happen if going between aoe and single target, or starting encounter with things on cd

All simple options ticked except for raid

**Comment by ele-starshade** [comment]
Hi @sauronshotdogs - Thanks for the report. I'll look into it and get back to you :)

**Comment by ele-starshade** [comment]
Hey @sauronshotdogs - I've pushed a potential fix out, let me know how it behaves :)

**Comment by sauronshotdogs** [comment]
Still gets stuck. Seems like it's either Raging Strikes, Battle Voice, Barrage or Radiant it will try to do, regardless of cd

**Comment by augporto** [comment]
From my understanding with the opener ticked you have to do the full opener before it goes back to normal behavior, the only way for now was to use an AOE gcd to bypass it , I remember when I was testing this for starshade, it was something I asked for because I found out that on DG it would do exactly that, "hang" on the opener until it was finished.

The behavior that we have today is that you are forced to do the opener if it is ticked, and the only way to bypass (after combat has started) is to use AOE gcd (mainly quick/ladons). 

Because if you want to start combat on ST you will just do the opener , its the optimal way. On DGs if you open with AOE itll bypass the opener and go with the normal behavior.

I believe that the opener as it is is not suited for open world , just DG, Raids and trails , as it should, when on open world just untick it, or use the aoe gcd.

**Comment by ele-starshade** [comment]
Give it a try with the latest update @sauronshotdogs - I've put a few more checks in there. Aug is correct though, for dungeons I usually turn the opener toggle off as it's not necessarily required. :)

**Comment by sauronshotdogs** [comment]
Will test when I get off later, thanks for the quick work!

**Comment by ele-starshade** [comment]
Thanks @sauronshotdogs! Closing this, any more issues let us know :)

**Comment by sauronshotdogs** [comment]
Will reopen, should the issues show again
