### ISSUE TITLE
[BLM] Minor issues

### ISSUE THREAD

**Issue by nativepapaya** [Nik-Potokar/XIVSlothCombo#343]
There are a couple of minor issues with the BLM rotation.

- If you have Astral Fire/Umbral Ice, but have less than 3 of either of them, the rotation will act as if you have 3 Astral Fire/Umbral ice and will never cast Fire 3 to give you 3 Astral Fire for example., and instead just go straight to Fire 4/blizzard 4.
- When Synced below level 35 (no blizzard 3), the rotation breaks when out of MP.
- Thunder 3 will try to override Thunder 4 and vice-versa.
- This one is hard to explain, but if you are out of MP, or below the threshold needed to cast another Fire spell, if you move before your next cast, instead of the rotation switching to Blizzard 3, it will just bug out and stay on Fire 4 even if 0 mp. This seems to happens randomly.

Small suggestion while we are at this.

- Would it be possible to add the option of automatically inserting Triplecast into the rotation when possible to weave? With the option to leave 1 stack unuse.

Thank you for the great plugin!

**Comment by k-kz** [comment]
> When Synced below level 35 (no blizzard 3), the rotation breaks when out of MP.

We're aware of this issue already, fix is in the pipeline.

> Would it be possible to add the option of automatically inserting Triplecast into the rotation when possible to weave? With the option to leave 1 stack unuse.

I also believe the Triplecast suggestion is a planned feature, but am not the one actively working on BLM.
Thanks very much for the other stuff! We'll get to it as soon as possible.

**Comment by nativepapaya** [comment]
No problem, thank you again for all the great features!

**Comment by Iaotle** [comment]
Another thing, Flare isn't used for the stance switcher. Is this intentional?

**Comment by grimgal** [comment]
I'll be taking a look into updating BLM with these new features!

**Comment by k-kz** [comment]
Fixed in #382

**Comment by nativepapaya** [comment]
Hi, i noticed that this bug is still present in the current version.

> If you have Astral Fire/Umbral Ice, but have less than 3 of either of them, the rotation will act as if you have 3 Astral Fire/Umbral ice and will never cast Fire 3 to give you 3 Astral Fire for example., and instead just go straight to Fire 4/blizzard 4.
