### ISSUE TITLE
PLD: Confiteor Feature

### ISSUE THREAD

**Issue by hokeenthong** [Nik-Potokar/XIVSlothCombo#65]
Hi. Tested this feature and the Holy Spirit / Circle does not change to Confiteor when Requiescat is up and (MP is under 2000 OR 1 stack remains). And of course,. it also does not add the Faith/Truth/Valor Combo. 

Thanks.

**Comment by hokeenthong** [comment]
On a related note, just realized this is now named as XIVslothCombo instead of XIVComboWayTooAkified. Are they the same?

**Comment by Nik-Potokar** [comment]
I've updated the name since its no longer for just personal use but yes they are the "same" but XIVComboWayTooAkified is outdated now.

So please use XIVslothCombo from now on

**Comment by Nik-Potokar** [comment]
Also i've just tested the feature to confirm and it does work.
It wont work if you have Fight Or Flight buff still on you tho since if you have that it assumes you are doing a physical combo not magical one

**Comment by hokeenthong** [comment]
Yes, I tested it when Fight or Flight is not on. 

Noted on the change of name, I will use XIVslothCombo from now onwards. 

Thank you.

**Comment by Nik-Potokar** [comment]
Thanks for the feedback il take a look once I'm home

**Comment by Nik-Potokar** [comment]
It should be fixed now 
(Cant test new PLD Confiteor comb since my PLD is still 80 but it should work )

**Comment by dnorthrupva** [comment]
Seems to be working now! I see what @hokeenthong meant - It wouldn't even leave Holy Spirit regardless of mana level.

**Comment by hokeenthong** [comment]
Hi, it is still not working. It is working on the Royal Authority Combo (All in one combo chain which includes the royal gloring option). In fact, it was working before. However, it is not working on the holy spirit or holy circle buttons. 

You might ask why would I need that if it is working on the all in one combo chain. Since requiescat is 30 sec now, there are reasons to delay the holy spirit combo after using requiescat for the holy spirit spam.

**Comment by Nik-Potokar** [comment]
Ahh I thought you meant the all in one option

So you just want me to add standalone options then right ? 

Also the all in one feature was made in mind with the delay(prepull strat) but I see how that wouldn't be always optimal in every content.

Il add in the standalone features in a bit

**Comment by hokeenthong** [comment]
Thanks. It is very useful in the all in one option but sometimes, it can benefit from the standalone as well. 

Thank you very much.

**Comment by Nik-Potokar** [comment]
Added the standalone options
If there is anything else please let me know.

**Comment by hokeenthong** [comment]
You are great! All good now. Thanks!
