### ISSUE TITLE
[BRD] 2 minutes "Raging Strikes, Barrage, Battle Voice, Radiant Finale" Only a few are used.

### ISSUE THREAD

**Issue by KouGithub2022** [Nik-Potokar/XIVSlothCombo#875]
The opening full burst is also not possible.
Of the four 2-minute abilities, only a few are used.

**Comment by augporto** [comment]
It should be fixed by #876 

Should go be on next release o/

**Comment by ron2453** [comment]
at least opener sometimes is still broken and do not use buffs in the beginning, please fix it. for the rest: great work and thanks a lot

**Comment by k-kz** [comment]
> at least opener sometimes is still broken and do not use buffs in the beginning, please fix it. for the rest: great work and thanks a lot

As @augporto commented above, a PR has been submitted and will be in the next stable release.

**Comment by k-kz** [comment]
Addressed in #876
